apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sa.yaml
- service.yaml
- statefulset.yaml
- rbac.yaml

configMapGenerator:
- name: java-elasticsearch-logging
  files:
  - java.security
