apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: keycloak
    role: persistence
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: keycloak
    role: persistence