apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
spec:
  type: LoadBalancer
  ports:
  - name: http
    nodePort: 30262
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32357
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    name: nginx-ingress-controller
