apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- cm.yaml
- ingress.yaml
- services.yaml
- statefulset.yaml

configMapGenerator:
- name: realm-export
  files:
  - realm-export.json

vars:
- name: POSTGRESQL
  objref:
    kind: Service
    name: postgresql
    apiVersion: v1