apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  ports:
  - name: alertmanager
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    name: alertmanager
  type: ClusterIP
